//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseCurriculum
    {
        public int CourseCurrID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string ChapterName { get; set; }
        public string LastUpdate { get; set; }
        public string FreeText1 { get; set; }
        public string FreeText2 { get; set; }
        public string FreeText3 { get; set; }
        public string Status { get; set; }
        public System.DateTime TMDate { get; set; }
    }
}
