//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        public int SubMenuID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string SubMenuName { get; set; }
        public string MenuLogo { get; set; }
        public string url { get; set; }
        public string FreeText1 { get; set; }
        public string FreeText2 { get; set; }
        public string FreeText3 { get; set; }
        public string Status { get; set; }
        public System.DateTime TMDate { get; set; }
    }
}
